//
// Generated file, do not edit! Created by nedtool 5.6 from echos.msg.
//

#ifndef __ECHOS_M_H
#define __ECHOS_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>echos.msg:1</tt> by nedtool.
 * <pre>
 * message echos
 * {
 *     int echonum;
 *     string sourcename;
 * }
 * </pre>
 */
class echos : public ::omnetpp::cMessage
{
  protected:
    int echonum;
    ::omnetpp::opp_string sourcename;

  private:
    void copy(const echos& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const echos&);

  public:
    echos(const char *name=nullptr, short kind=0);
    echos(const echos& other);
    virtual ~echos();
    echos& operator=(const echos& other);
    virtual echos *dup() const override {return new echos(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getEchonum() const;
    virtual void setEchonum(int echonum);
    virtual const char * getSourcename() const;
    virtual void setSourcename(const char * sourcename);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const echos& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, echos& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ECHOS_M_H

